apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m84tsk62u-python 
  janus-idp.io/tekton: m84tsk62u-python
  backstage.io/kubernetes-id: m84tsk62u-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m84tsk62u-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  