apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: m84tsk62u-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:4bc4d8fac43c5d7e4e21af841bf40483863b844e@sha256:0dd6bd28196fa8cfc4aec699cadf572954153ee964b982a0dd49be0707a745aa
          name: container-image
